spring.application.name=DuocBibliotecaa

# Conexion a Neon PostgreSQL
spring.datasource.url=jdbc:postgresql://ep-still-water-atq9wc81-pooler.c-9.us-east-1.aws.neon.tech/neondb?sslmode=require&channel_binding=require
spring.datasource.username=neondb_owner
spring.datasource.password=npg_x7QqkcT2JGAg
spring.datasource.driver-class-name=org.postgresql.Driver

# Configuracion JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Configuracion general
spring.jackson.serialization.fail-on-empty-beans=false
spring.threads.virtual.enabled=true
spring.mvc.problemdetails.enabled=false

# Logs
logging.pattern.console=%d{yyyy-MM-dd HH:mm:ss} - %msg%n